(c-declare "#include <stdlib.h>")
(c-declare "#include \"/usr/local/include/IL/il.h\"")
(include "ffi-prelude.scm")
(define-constant IL_FALSE int)
(define-constant IL_TRUE int)
(define-constant IL_COLOUR_INDEX int)
(define-constant IL_COLOR_INDEX int)
(define-constant IL_RGB int)
(define-constant IL_RGBA int)
(define-constant IL_BGR int)
(define-constant IL_BGRA int)
(define-constant IL_LUMINANCE int)
(define-constant IL_LUMINANCE_ALPHA int)
(define-constant IL_BYTE int)
(define-constant IL_UNSIGNED_BYTE int)
(define-constant IL_SHORT int)
(define-constant IL_UNSIGNED_SHORT int)
(define-constant IL_INT int)
(define-constant IL_UNSIGNED_INT int)
(define-constant IL_FLOAT int)
(define-constant IL_DOUBLE int)
(define-constant IL_HALF int)
(define-constant IL_VENDOR int)
(define-constant IL_LOAD_EXT int)
(define-constant IL_SAVE_EXT int)
(define-constant IL_VERSION_1_7_4 int)
(define-constant IL_VERSION int)
(define-constant IL_ORIGIN_BIT int)
(define-constant IL_FILE_BIT int)
(define-constant IL_PAL_BIT int)
(define-constant IL_FORMAT_BIT int)
(define-constant IL_TYPE_BIT int)
(define-constant IL_COMPRESS_BIT int)
(define-constant IL_LOADFAIL_BIT int)
(define-constant IL_FORMAT_SPECIFIC_BIT int)
(define-constant IL_ALL_ATTRIB_BITS int)
(define-constant IL_PAL_NONE int)
(define-constant IL_PAL_RGB24 int)
(define-constant IL_PAL_RGB32 int)
(define-constant IL_PAL_RGBA32 int)
(define-constant IL_PAL_BGR24 int)
(define-constant IL_PAL_BGR32 int)
(define-constant IL_PAL_BGRA32 int)
(define-constant IL_TYPE_UNKNOWN int)
(define-constant IL_BMP int)
(define-constant IL_CUT int)
(define-constant IL_DOOM int)
(define-constant IL_DOOM_FLAT int)
(define-constant IL_ICO int)
(define-constant IL_JPG int)
(define-constant IL_JFIF int)
(define-constant IL_LBM int)
(define-constant IL_PCD int)
(define-constant IL_PCX int)
(define-constant IL_PIC int)
(define-constant IL_PNG int)
(define-constant IL_PNM int)
(define-constant IL_SGI int)
(define-constant IL_TGA int)
(define-constant IL_TIF int)
(define-constant IL_CHEAD int)
(define-constant IL_RAW int)
(define-constant IL_MDL int)
(define-constant IL_WAL int)
(define-constant IL_LIF int)
(define-constant IL_MNG int)
(define-constant IL_JNG int)
(define-constant IL_GIF int)
(define-constant IL_DDS int)
(define-constant IL_DCX int)
(define-constant IL_PSD int)
(define-constant IL_EXIF int)
(define-constant IL_PSP int)
(define-constant IL_PIX int)
(define-constant IL_PXR int)
(define-constant IL_XPM int)
(define-constant IL_HDR int)
(define-constant IL_ICNS int)
(define-constant IL_JP2 int)
(define-constant IL_EXR int)
(define-constant IL_WDP int)
(define-constant IL_JASC_PAL int)
(define-constant IL_NO_ERROR int)
(define-constant IL_INVALID_ENUM int)
(define-constant IL_OUT_OF_MEMORY int)
(define-constant IL_FORMAT_NOT_SUPPORTED int)
(define-constant IL_INTERNAL_ERROR int)
(define-constant IL_INVALID_VALUE int)
(define-constant IL_ILLEGAL_OPERATION int)
(define-constant IL_ILLEGAL_FILE_VALUE int)
(define-constant IL_INVALID_FILE_HEADER int)
(define-constant IL_INVALID_PARAM int)
(define-constant IL_COULD_NOT_OPEN_FILE int)
(define-constant IL_INVALID_EXTENSION int)
(define-constant IL_FILE_ALREADY_EXISTS int)
(define-constant IL_OUT_FORMAT_SAME int)
(define-constant IL_STACK_OVERFLOW int)
(define-constant IL_STACK_UNDERFLOW int)
(define-constant IL_INVALID_CONVERSION int)
(define-constant IL_BAD_DIMENSIONS int)
(define-constant IL_FILE_READ_ERROR int)
(define-constant IL_FILE_WRITE_ERROR int)
(define-constant IL_LIB_GIF_ERROR int)
(define-constant IL_LIB_JPEG_ERROR int)
(define-constant IL_LIB_PNG_ERROR int)
(define-constant IL_LIB_TIFF_ERROR int)
(define-constant IL_LIB_MNG_ERROR int)
(define-constant IL_LIB_JP2_ERROR int)
(define-constant IL_UNKNOWN_ERROR int)
(define-constant IL_ORIGIN_SET int)
(define-constant IL_ORIGIN_LOWER_LEFT int)
(define-constant IL_ORIGIN_UPPER_LEFT int)
(define-constant IL_ORIGIN_MODE int)
(define-constant IL_FORMAT_SET int)
(define-constant IL_FORMAT_MODE int)
(define-constant IL_TYPE_SET int)
(define-constant IL_TYPE_MODE int)
(define-constant IL_FILE_OVERWRITE int)
(define-constant IL_FILE_MODE int)
(define-constant IL_CONV_PAL int)
(define-constant IL_DEFAULT_ON_FAIL int)
(define-constant IL_USE_KEY_COLOUR int)
(define-constant IL_USE_KEY_COLOR int)
(define-constant IL_BLIT_BLEND int)
(define-constant IL_SAVE_INTERLACED int)
(define-constant IL_INTERLACE_MODE int)
(define-constant IL_QUANTIZATION_MODE int)
(define-constant IL_WU_QUANT int)
(define-constant IL_NEU_QUANT int)
(define-constant IL_NEU_QUANT_SAMPLE int)
(define-constant IL_MAX_QUANT_INDEXS int)
(define-constant IL_FASTEST int)
(define-constant IL_LESS_MEM int)
(define-constant IL_DONT_CARE int)
(define-constant IL_MEM_SPEED_HINT int)
(define-constant IL_USE_COMPRESSION int)
(define-constant IL_NO_COMPRESSION int)
(define-constant IL_COMPRESSION_HINT int)
(define-constant IL_SUB_NEXT int)
(define-constant IL_SUB_MIPMAP int)
(define-constant IL_SUB_LAYER int)
(define-constant IL_COMPRESS_MODE int)
(define-constant IL_COMPRESS_NONE int)
(define-constant IL_COMPRESS_RLE int)
(define-constant IL_COMPRESS_LZO int)
(define-constant IL_COMPRESS_ZLIB int)
(define-constant IL_TGA_CREATE_STAMP int)
(define-constant IL_JPG_QUALITY int)
(define-constant IL_PNG_INTERLACE int)
(define-constant IL_TGA_RLE int)
(define-constant IL_BMP_RLE int)
(define-constant IL_SGI_RLE int)
(define-constant IL_TGA_ID_STRING int)
(define-constant IL_TGA_AUTHNAME_STRING int)
(define-constant IL_TGA_AUTHCOMMENT_STRING int)
(define-constant IL_PNG_AUTHNAME_STRING int)
(define-constant IL_PNG_TITLE_STRING int)
(define-constant IL_PNG_DESCRIPTION_STRING int)
(define-constant IL_TIF_DESCRIPTION_STRING int)
(define-constant IL_TIF_HOSTCOMPUTER_STRING int)
(define-constant IL_TIF_DOCUMENTNAME_STRING int)
(define-constant IL_TIF_AUTHNAME_STRING int)
(define-constant IL_JPG_SAVE_FORMAT int)
(define-constant IL_CHEAD_HEADER_STRING int)
(define-constant IL_PCD_PICNUM int)
(define-constant IL_JPG_PROGRESSIVE int)
(define-constant IL_PNG_ALPHA_INDEX int)
(define-constant IL_DXTC_FORMAT int)
(define-constant IL_DXT1 int)
(define-constant IL_DXT2 int)
(define-constant IL_DXT3 int)
(define-constant IL_DXT4 int)
(define-constant IL_DXT5 int)
(define-constant IL_DXT_NO_COMP int)
(define-constant IL_KEEP_DXTC_DATA int)
(define-constant IL_DXTC_DATA_FORMAT int)
(define-constant IL_3DC int)
(define-constant IL_RXGB int)
(define-constant IL_ATI1N int)
(define-constant IL_CUBEMAP_POSITIVEX int)
(define-constant IL_CUBEMAP_NEGATIVEX int)
(define-constant IL_CUBEMAP_POSITIVEY int)
(define-constant IL_CUBEMAP_NEGATIVEY int)
(define-constant IL_CUBEMAP_POSITIVEZ int)
(define-constant IL_CUBEMAP_NEGATIVEZ int)
(define-constant IL_VERSION_NUM int)
(define-constant IL_IMAGE_WIDTH int)
(define-constant IL_IMAGE_HEIGHT int)
(define-constant IL_IMAGE_DEPTH int)
(define-constant IL_IMAGE_SIZE_OF_DATA int)
(define-constant IL_IMAGE_BPP int)
(define-constant IL_IMAGE_BYTES_PER_PIXEL int)
(define-constant IL_IMAGE_BPP int)
(define-constant IL_IMAGE_BITS_PER_PIXEL int)
(define-constant IL_IMAGE_FORMAT int)
(define-constant IL_IMAGE_TYPE int)
(define-constant IL_PALETTE_TYPE int)
(define-constant IL_PALETTE_SIZE int)
(define-constant IL_PALETTE_BPP int)
(define-constant IL_PALETTE_NUM_COLS int)
(define-constant IL_PALETTE_BASE_TYPE int)
(define-constant IL_NUM_IMAGES int)
(define-constant IL_NUM_MIPMAPS int)
(define-constant IL_NUM_LAYERS int)
(define-constant IL_ACTIVE_IMAGE int)
(define-constant IL_ACTIVE_MIPMAP int)
(define-constant IL_ACTIVE_LAYER int)
(define-constant IL_CUR_IMAGE int)
(define-constant IL_IMAGE_DURATION int)
(define-constant IL_IMAGE_PLANESIZE int)
(define-constant IL_IMAGE_BPC int)
(define-constant IL_IMAGE_OFFX int)
(define-constant IL_IMAGE_OFFY int)
(define-constant IL_IMAGE_CUBEFLAGS int)
(define-constant IL_IMAGE_ORIGIN int)
(define-constant IL_IMAGE_CHANNELS int)
(define-constant IL_SEEK_SET int)
(define-constant IL_SEEK_CUR int)
(define-constant IL_SEEK_END int)
(define-constant IL_EOF int)
(c-define-type ILenum unsigned-int)
(c-define-type ILboolean unsigned-char)
(c-define-type ILbitfield unsigned-int)
(c-define-type ILbyte signed)
(c-define-type ILshort short)
(c-define-type ILint int)
(c-define-type ILsizei size_t)
(c-define-type ILubyte unsigned-char)
(c-define-type ILushort unsigned-short)
(c-define-type ILuint unsigned-int)
(c-define-type ILfloat float)
(c-define-type ILclampf float)
(c-define-type ILdouble double)
(c-define-type ILclampd double)
(c-define-type ILHANDLE (pointer void))
(c-define-type fCloseRProc (function (ILHANDLE) void))
(c-define-type fEofProc (function (ILHANDLE) ILboolean))
(c-define-type fGetcProc (function (ILHANDLE) ILint))
(c-define-type fOpenRProc (function ((pointer (const char))) ILHANDLE))
(c-define-type fReadProc (function ((pointer void) ILuint ILuint ILHANDLE) ILint))
(c-define-type fSeekRProc (function (ILHANDLE ILint ILint) ILint))
(c-define-type fTellRProc (function (ILHANDLE) ILint))
(c-define-type fCloseWProc (function (ILHANDLE) void))
(c-define-type fOpenWProc (function ((pointer (const char))) ILHANDLE))
(c-define-type fPutcProc (function (ILubyte ILHANDLE) ILint))
(c-define-type fSeekWProc (function (ILHANDLE ILint ILint) ILint))
(c-define-type fTellWProc (function (ILHANDLE) ILint))
(c-define-type fWriteProc (function ((pointer (const void)) ILuint ILuint ILHANDLE) ILint))
(c-define-type mAlloc (function ((const ILsizei)) (pointer void)))
(c-define-type mFree (function ((const (pointer (const void)))) void))
(c-define-type IL_LOADPROC (function ((pointer (const char))) ILenum))
(c-define-type IL_SAVEPROC (function ((pointer (const char))) ILenum))
(define ilActiveImage (c-lambda (ILuint) ILboolean "ilActiveImage"))
(define ilActiveLayer (c-lambda (ILuint) ILboolean "ilActiveLayer"))
(define ilActiveMipmap (c-lambda (ILuint) ILboolean "ilActiveMipmap"))
(define ilApplyPal (c-lambda ((pointer (const char))) ILboolean "ilApplyPal"))
(define ilApplyProfile (c-lambda ((pointer char) (pointer char)) ILboolean "ilApplyProfile"))
(define ilBindImage (c-lambda (ILuint) void "ilBindImage"))
(define ilBlit (c-lambda (ILuint ILint ILint ILint ILuint ILuint ILuint ILuint ILuint ILuint) ILboolean "ilBlit"))
(define ilClearColour (c-lambda (ILclampf ILclampf ILclampf ILclampf) void "ilClearColour"))
(define ilClearImage (c-lambda () ILboolean "ilClearImage"))
(define ilCloneCurImage (c-lambda () ILuint "ilCloneCurImage"))
(define ilCompressFunc (c-lambda (ILenum) ILboolean "ilCompressFunc"))
(define ilConvertImage (c-lambda (ILenum ILenum) ILboolean "ilConvertImage"))
(define ilConvertPal (c-lambda (ILenum) ILboolean "ilConvertPal"))
(define ilCopyImage (c-lambda (ILuint) ILboolean "ilCopyImage"))
(define ilCopyPixels (c-lambda (ILuint ILuint ILuint ILuint ILuint ILuint ILenum ILenum (pointer void)) ILuint "ilCopyPixels"))
(define ilCreateSubImage (c-lambda (ILenum ILuint) ILuint "ilCreateSubImage"))
(define ilDefaultImage (c-lambda () ILboolean "ilDefaultImage"))
(define ilDeleteImage (c-lambda ((const ILuint)) void "ilDeleteImage"))
(define ilDeleteImages (c-lambda (ILsizei (pointer (const ILuint))) void "ilDeleteImages"))
(define ilDisable (c-lambda (ILenum) ILboolean "ilDisable"))
(define ilEnable (c-lambda (ILenum) ILboolean "ilEnable"))
(define ilFormatFunc (c-lambda (ILenum) ILboolean "ilFormatFunc"))
(define ilGenImages (c-lambda (ILsizei (pointer ILuint)) void "ilGenImages"))
(define ilGenImage (c-lambda () ILuint "ilGenImage"))
(define ilGetAlpha (c-lambda (ILenum) (pointer ILubyte) "ilGetAlpha"))
(define ilGetBoolean (c-lambda (ILenum) ILboolean "ilGetBoolean"))
(define ilGetBooleanv (c-lambda (ILenum (pointer ILboolean)) void "ilGetBooleanv"))
(define ilGetData (c-lambda () (pointer ILubyte) "ilGetData"))
(define ilGetDXTCData (c-lambda ((pointer void) ILuint ILenum) ILuint "ilGetDXTCData"))
(define ilGetError (c-lambda () ILenum "ilGetError"))
(define ilGetInteger (c-lambda (ILenum) ILint "ilGetInteger"))
(define ilGetIntegerv (c-lambda (ILenum (pointer ILint)) void "ilGetIntegerv"))
(define ilGetLumpPos (c-lambda () ILuint "ilGetLumpPos"))
(define ilGetPalette (c-lambda () (pointer ILubyte) "ilGetPalette"))
(define ilGetString (c-lambda (ILenum) (pointer char) "ilGetString"))
(define ilHint (c-lambda (ILenum ILenum) void "ilHint"))
(define ilInit (c-lambda () void "ilInit"))
(define ilIsDisabled (c-lambda (ILenum) ILboolean "ilIsDisabled"))
(define ilIsEnabled (c-lambda (ILenum) ILboolean "ilIsEnabled"))
(define ilDetermineTypeF (c-lambda (ILHANDLE) ILenum "ilDetermineTypeF"))
(define ilIsImage (c-lambda (ILuint) ILboolean "ilIsImage"))
(define ilIsValid (c-lambda (ILenum (pointer char)) ILboolean "ilIsValid"))
(define ilIsValidF (c-lambda (ILenum ILHANDLE) ILboolean "ilIsValidF"))
(define ilIsValidL (c-lambda (ILenum (pointer void) ILuint) ILboolean "ilIsValidL"))
(define ilKeyColour (c-lambda (ILclampf ILclampf ILclampf ILclampf) void "ilKeyColour"))
(define ilLoad (c-lambda (ILenum (pointer (const char))) ILboolean "ilLoad"))
(define ilLoadF (c-lambda (ILenum ILHANDLE) ILboolean "ilLoadF"))
(define ilLoadImage (c-lambda ((pointer (const char))) ILboolean "ilLoadImage"))
(define ilLoadL (c-lambda (ILenum (pointer (const void)) ILuint) ILboolean "ilLoadL"))
(define ilLoadPal (c-lambda ((pointer (const char))) ILboolean "ilLoadPal"))
(define ilModAlpha (c-lambda (ILdouble) void "ilModAlpha"))
(define ilOriginFunc (c-lambda (ILenum) ILboolean "ilOriginFunc"))
(define ilOverlayImage (c-lambda (ILuint ILint ILint ILint) ILboolean "ilOverlayImage"))
(define ilPopAttrib (c-lambda () void "ilPopAttrib"))
(define ilPushAttrib (c-lambda (ILuint) void "ilPushAttrib"))
(define ilRegisterFormat (c-lambda (ILenum) void "ilRegisterFormat"))
(define ilRegisterLoad (c-lambda ((pointer (const char)) IL_LOADPROC) ILboolean "ilRegisterLoad"))
(define ilRegisterMipNum (c-lambda (ILuint) ILboolean "ilRegisterMipNum"))
(define ilRegisterNumImages (c-lambda (ILuint) ILboolean "ilRegisterNumImages"))
(define ilRegisterOrigin (c-lambda (ILenum) void "ilRegisterOrigin"))
(define ilRegisterPal (c-lambda ((pointer void) ILuint ILenum) void "ilRegisterPal"))
(define ilRegisterSave (c-lambda ((pointer (const char)) IL_SAVEPROC) ILboolean "ilRegisterSave"))
(define ilRegisterType (c-lambda (ILenum) void "ilRegisterType"))
(define ilRemoveLoad (c-lambda ((pointer (const char))) ILboolean "ilRemoveLoad"))
(define ilRemoveSave (c-lambda ((pointer (const char))) ILboolean "ilRemoveSave"))
(define ilResetMemory (c-lambda () void "ilResetMemory"))
(define ilResetRead (c-lambda () void "ilResetRead"))
(define ilResetWrite (c-lambda () void "ilResetWrite"))
(define ilSave (c-lambda (ILenum (pointer char)) ILboolean "ilSave"))
(define ilSaveF (c-lambda (ILenum ILHANDLE) ILuint "ilSaveF"))
(define ilSaveImage (c-lambda ((pointer (const char))) ILboolean "ilSaveImage"))
(define ilSaveL (c-lambda (ILenum (pointer void) ILuint) ILuint "ilSaveL"))
(define ilSavePal (c-lambda ((pointer (const char))) ILboolean "ilSavePal"))
(define ilSetAlpha (c-lambda (ILdouble) ILboolean "ilSetAlpha"))
(define ilSetData (c-lambda ((pointer void)) ILboolean "ilSetData"))
(define ilSetDuration (c-lambda (ILuint) ILboolean "ilSetDuration"))
(define ilSetInteger (c-lambda (ILenum ILint) void "ilSetInteger"))
(define ilSetMemory (c-lambda (mAlloc mFree) void "ilSetMemory"))
(define ilSetPixels (c-lambda (ILint ILint ILint ILuint ILuint ILuint ILenum ILenum (pointer void)) void "ilSetPixels"))
(define ilSetRead (c-lambda (fOpenRProc fCloseRProc fEofProc fGetcProc fReadProc fSeekRProc fTellRProc) void "ilSetRead"))
(define ilSetString (c-lambda (ILenum (pointer (const char))) void "ilSetString"))
(define ilSetWrite (c-lambda (fOpenWProc fCloseWProc fPutcProc fSeekWProc fTellWProc fWriteProc) void "ilSetWrite"))
(define ilShutDown (c-lambda () void "ilShutDown"))
(define ilTexImage (c-lambda (ILuint ILuint ILuint ILubyte ILenum ILenum (pointer void)) ILboolean "ilTexImage"))
(define ilTypeFromExt (c-lambda ((pointer (const char))) ILenum "ilTypeFromExt"))
(define ilTypeFunc (c-lambda (ILenum) ILboolean "ilTypeFunc"))
(define ilLoadData (c-lambda ((pointer (const char)) ILuint ILuint ILuint ILubyte) ILboolean "ilLoadData"))
(define ilLoadDataF (c-lambda (ILHANDLE ILuint ILuint ILuint ILubyte) ILboolean "ilLoadDataF"))
(define ilLoadDataL (c-lambda ((pointer void) ILuint ILuint ILuint ILuint ILubyte) ILboolean "ilLoadDataL"))
(define ilSaveData (c-lambda ((pointer (const char))) ILboolean "ilSaveData"))
